#!/bin/sh
export OSU_INSTALL_LOCATION="$HOME/.local/share/osu-stable/"

mkdir -p "$HOME/.local/share/wineprefixes/"

export vblank_mode=0
export __GL_SYNC_TO_VBLANK=0

export WINEPREFIX="$HOME/.local/share/wineprefixes/osu-stable"
export WINEARCH=win32 

if [ ! -f "$HOME/.local/share/applications/osu-stable.desktop" ]
then
    mkdir -p "$HOME/.local/share/applications/"
    echo "[Desktop Entry]
          Type=Application
          Name=osu!
          Icon=osu-stable.png
          Exec=osu-stable %U
          Categories=Game;
          StartupWMClass=osu!.exe
          MimeType=x-scheme-handler/osu" > "$HOME/.local/share/applications/osu-stable.desktop"
fi

if [ ! -f "$HOME/.local/share/icons/osu-stable.png" ]
then
    mkdir -p "$HOME/.local/share/icons/"
    wget -O "$HOME/.local/share/icons/osu-stable.png" "https://i.imgur.com/Rswh32I.png"
fi

if [ ! -d "$OSU_INSTALL_LOCATION" ]
then
    mkdir -p $OSU_INSTALL_LOCATION
    wget -O "$OSU_INSTALL_LOCATION/osu!.exe" "https://m1.ppy.sh/r/osu!install.exe"
fi

if [ ! -d "$WINEPREFIX" ]
then
    winetricks -q --force cjkfonts arial vlgothic meiryo tahoma sourcehansans gdiplus dotnet48
    wine reg add "HKCU\Software\Wine\DirectSound" /v "HelBuflen" /t REG_SZ /d "512" /f
    wine reg add "HKCU\Software\Wine\DirectSound" /v "SndQueueMax" /t REG_SZ /d "3" /f 
    # winetricks sound=alsa
fi

cd $OSU_INSTALL_LOCATION
wine "osu!.exe" "$@"
